### ISSUE TITLE
Percentile Calculations

### ISSUE THREAD

**Issue by Gbird22** [corybuecker/ruby-native-statistics#27]
I was using your module to calculate some statistics and the results for the percentile function aren't quite what I expected.  This could be a misunderstanding on my part, but I'm not sure.  Here's the code that I'm running and the results are below.  Thanks in advance.  

**Code**: 

require 'ruby_native_statistics'
b = [1,2,3,4,5,6,7,8,9,10]
r= [5.4, 5.3, 5.2, 5.4, 5.2, 4.6, 4.7, 5.0, 5.1, 5.0, 5.4, 4.6, 5.2, 4.6, 4.7, 5.2, 5.4, 5.0, 5.3, 5.3, 6.0, 5.1, 5.5, 5.5, 5.5, 5.6, 5.8, 5.2, 4.9, 5.5, 5.7, 5.9]

# calculate percentile
p b
p b.percentile(0.90)
p b.percentile(0.50)
p b.percentile(0.10)

# calculate percentile
p r
p r.percentile(0.90)
p r.percentile(0.50)
p r.percentile(0.10)

**Output**
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
9.1
5.5
1.9000000000000001
[5.4, 5.3, 5.2, 5.4, 5.2, 4.6, 4.7, 5.0, 5.1, 5.0, 5.4, 4.6, 5.2, 4.6, 4.7, 5.2, 5.4, 5.0, 5.3, 5.3, 6.0, 5.1, 5.5, 5.5, 5.5, 5.6, 5.8, 5.2, 4.9, 5.5, 5.7, 5.9]
5.21
5.55
4.609999999999999

**Comment by corybuecker** [comment]
Thanks for reporting this! Could you try version 1.1.0?

**Comment by Gbird22** [comment]
That did the trick.  Thanks for a well thought out and useful module that saved me a ton of time.  Cheers!

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
9.1
5.5
1.9000000000000001
[5.4, 5.3, 5.2, 5.4, 5.2, 4.6, 4.7, 5.0, 5.1, 5.0, 5.4, 4.6, 5.2, 4.6, 4.7, 5.2, 5.4, 5.0, 5.3, 5.3, 6.0, 5.1, 5.5, 5.5, 5.5, 5.6, 5.8, 5.2, 4.9, 5.5, 5.7, 5.9]
5.69
5.25
4.7

**Comment by corybuecker** [comment]
Glad it worked and is useful. I mainly built this for learning C, so if you need other functions, please let me know.
